# Generated by Django 3.2.18 on 2023-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
